// Re-export commonly used icons
export { 
  FiHome, 
  FiSearch, 
  FiFilter, 
  FiTrash, 
  FiDownload, 
  FiMap, 
  FiSun, 
  FiMoon,
  FiCheck,
  FiAlertTriangle,
  FiHeadphones,
  FiCalendar,
  FiClipboard,
  FiSettings,
  FiBookOpen,
  FiPlus,
  FiPlusCircle,
  FiSliders,
  FiShield,
  FiChevronLeft,
  FiChevronRight,
  FiMenu,
  FiX,
  FiUser,
  FiBell,
  FiEye,
  FiEyeOff,
  FiSave,
  FiRefreshCw,
  FiGlobe,
  FiLock,
  FiUnlock
} from 'react-icons/fi';

// Export with alternative names for compatibility
export { 
  FiHome as HomeIcon,
  FiCalendar as CalendarIcon,
  FiClipboard as ClipboardListIcon,
  FiSettings as CogIcon,
  FiBookOpen as BookOpenIcon,
  FiPlus as PlusIcon,
  FiPlusCircle as PlusCircleIcon,
  FiSliders as AdjustmentsHorizontalIcon,
  FiShield as ShieldCheckIcon,
  FiChevronLeft as ChevronLeftIcon,
  FiChevronRight as ChevronRightIcon,
  FiMenu as Bars3Icon,
  FiX as XMarkIcon,
  FiUser as UserIcon,
  FiBell as BellIcon,
  FiEye as EyeIcon,
  FiEyeOff as EyeSlashIcon,
  FiSliders as PaintBrushIcon,
  FiSun as SunIcon,
  FiMoon as MoonIcon,
  FiSave as SaveIcon,
  FiRefreshCw as RefreshCwIcon,
  FiGlobe as GlobeIcon,
  FiLock as LockIcon,
  FiUnlock as UnlockIcon
} from 'react-icons/fi';